version: "3"
services:
  warp-test-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres_password'
  warp-test-wsgi:
    build: .
    depends_on:
    - warp-test-db
    environment:
      WARP_DATABASE: "postgresql://postgres:postgres_password@warp-test-db:5432/postgres"
      WARP_SECRET_KEY: 'mysecretkey'
      WARP_DATABASE_INIT_SCRIPT: '["sql/schema.sql","sql/sample_data.sql"]'
      WARP_LANGUAGE_FILE: 'i18n/en.js'
      WARP_OMITTED_WEEKDAYS: '[5,6]'
      WARP_BOOK_OPEN: 21600
      WARP_BOOK_CLOSE: 72000
  warp-test-nginx:
    image: nginx
    depends_on:
    - warp-test-wsgi
    volumes:
      - ./res/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
